apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: wsapp-ingress
  namespace: default
  annotations:
    nginx.org/websocket-services: "wsserver-svc"

spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.ingressDomain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wsclient-svc
                port:
                  number: 80
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: wsserver-svc
                port:
                  number: 80
