apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack-depl
  labels:
    app: redis-stack-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-stack
  template:
    metadata:
      labels:
        app: redis-stack
    spec:
      containers:
        - name: redis
          image: redis/redis-stack:latest
          ports:
            - containerPort: 6379
            - containerPort: 8001
