apiVersion: v1
kind: Service
metadata:
  name: redis-stack-svc
  namespace: default
spec:
  selector:
    app: redis-stack
  ports:
    - name: redis-server
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: redis-gui
      protocol: TCP
      port: 6379
      targetPort: 6379
