apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsclient-depl
  labels:
    app: wsclient-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wsclient
  template:
    metadata:
      labels:
        app: wsclient
    spec:
      containers:
        - name: wsclient
          image: aaraz/wsclient:1.1
          ports:
            - containerPort: 3000
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: wsclient-config
                  key: BASE_URL
